name: DDPM For Background Correction

data_settings:
  train_data_dir: training_data
  model_save_dir: checkpoints
  img_size: 256
  dataset_init_every_n_epoch: 2
  model_save_every_n_step: 5000
  pretrained_weight: checkpoints/ddpm_pair_v3_400K.pt

model_settings:
  ch: 64
  ch_mult: [1, 2, 2, 4, 4]
  num_res_blocks: 2
  dropout: 0.
  attn_ds: [16]
  use_torch_attn: False
  size: 256
  input_ch: 3

training_settings:
  use_mix_precision: true
  weight_decay: 1.e-4
  lr: 4.5e-6
  grad_clip: 1.
  batch_size: 4
  accumulate_step: 2
  epoch: 1000

ddpm_settings:
  T: 1000
  beta_scdl: linear
  beta_1: 1.e-4
  beta_T: 0.02
  uncon_ratio: 0.1