name: DDPM For Background Correction

data_settings:
  train_dref_data: training_data/sample
  train_ref_data: training_data/TXM_2025_reference
  train_size: 10000
  model_save_dir: checkpoints
  pretrained_weight: ~
  img_size: 256
  
model_settings:
  ch: 64
  ch_mult: [1, 2, 2, 4, 4]
  num_res_blocks: 2
  dropout: 0.
  attn_ds: [16]
  use_torch_attn: False
  size: 256
  input_ch: 3

training_settings:
  model_save_every_n_step: 5000
  use_mix_precision: true
  weight_decay: 1.e-4
  lr: 4.5e-6
  grad_clip: 1.
  batch_size: 6
  accumulate_step: 2
  epoch: 1000

ddpm_settings:
  T: 1000
  beta_scdl: linear
  beta_1: 1.e-4
  beta_T: 0.02
  uncon_ratio: 0.1